// ASCII art with colors from original image
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const WELCOME_ASCII_LINES = [
  {
    segments: [
      { text: '                                                                                ' },
    ],
  },
  {
    segments: [
      { text: '                                                                                ' },
    ],
  },
  {
    segments: [
      { text: '                         ' },
      { text: '.', color: '#2f1c00' },
      { text: '.', color: '#452a00' },
      { text: '.', color: '#472b00' },
      { text: '.', color: '#452a00' },
      { text: '.', color: '#432900' },
      { text: '.', color: '#442900' },
      { text: '.', color: '#4c2e00' },
      { text: '             ' },
      { text: ':', color: '#a56400' },
      { text: '+', color: '#f29300' },
      { text: '+', color: '#f09100' },
      { text: '+', color: '#ee9000' },
      { text: '+', color: '#ec8f00' },
      { text: '+', color: '#ea8e00' },
      { text: '+', color: '#e78c00' },
      { text: '+', color: '#e58b00' },
      { text: '+', color: '#e38a00' },
      { text: '+', color: '#e18800' },
      { text: '+', color: '#df8700' },
      { text: '+', color: '#dd8600' },
      { text: '+', color: '#da8400' },
      { text: ';', color: '#d88300' },
      { text: ':', color: '#9f6000' },
      { text: '          ' },
      { text: '.', color: '#311e00' },
      { text: '         ' },
    ],
  },
  {
    segments: [
      { text: '                         ' },
      { text: ':', color: '#a96700' },
      { text: '++++++', color: '#f69500' },
      { text: '.', color: '#352000' },
      { text: '            ' },
      { text: ';', color: '#cd7c00' },
      { text: '+++++++++++++', color: '#f69500' },
      { text: '+', color: '#f39300' },
      { text: '     ' },
      { text: '+', color: '#ed9000' },
      { text: '+++++', color: '#f69500' },
      { text: '         ' },
    ],
  },
  {
    segments: [
      { text: '              ' },
      { text: '.', color: '#320c09' },
      { text: '.', color: '#360d09' },
      { text: '.', color: '#370d0a' },
      { text: '.', color: '#330c09' },
      { text: '       ' },
      { text: ':', color: '#945a00' },
      { text: '++++++', color: '#f69500' },
      { text: '.', color: '#472b00' },
      { text: '            ' },
      { text: '.', color: '#4e2f00' },
      { text: '.', color: '#4b2d00' },
      { text: '.', color: '#482b00' },
      { text: '.', color: '#472b00' },
      { text: '.', color: '#492c00' },
      { text: '.', color: '#4a2d00' },
      { text: ',', color: '#7c4b00' },
      { text: '++++++++', color: '#f69500' },
      { text: ',', color: '#814e00' },
      { text: '   ' },
      { text: ',', color: '#784900' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#6a4000' },
      { text: '        ' },
    ],
  },
  {
    segments: [
      { text: '      ' },
      { text: ',', color: '#6d1a13' },
      { text: ':', color: '#a3271d' },
      { text: ';', color: '#c73023' },
      { text: ';', color: '#de3527' },
      { text: ';', color: '#e93829' },
      { text: ';;;;;;;;;', color: '#ea3829' },
      { text: ';', color: '#d53325' },
      { text: ',', color: '#872018' },
      { text: '   ' },
      { text: ':', color: '#865100' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#583500' },
      { text: '         ' },
      { text: '+', color: '#e88d00' },
      { text: '+', color: '#e98d00' },
      { text: '+', color: '#e58b00' },
      { text: '+', color: '#df8700' },
      { text: ';', color: '#d88300' },
      { text: ';', color: '#d17e00' },
      { text: ',', color: '#734600' },
      { text: '  ' },
      { text: ',', color: '#7f4d00' },
      { text: '++++++++', color: '#f69500' },
      { text: '+', color: '#ed9000' },
      { text: '   ' },
      { text: '+', color: '#e78c00' },
      { text: '++++++', color: '#f69500' },
      { text: ';', color: '#b16b00' },
      { text: '        ' },
    ],
  },
  {
    segments: [
      { text: '     ' },
      { text: ';', color: '#d03224' },
      { text: ';;;;;;;;;;;;;;;;', color: '#ea3829' },
      { text: ';', color: '#c83023' },
      { text: '  ' },
      { text: ',', color: '#7b4a00' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#663e00' },
      { text: '         ' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#8b5400' },
      { text: '  ' },
      { text: ';', color: '#af6a00' },
      { text: '+++++++++', color: '#f69500' },
      { text: ':', color: '#ab6800' },
      { text: ' ' },
      { text: ';', color: '#ae6900' },
      { text: '+++++++', color: '#f69500' },
      { text: '+', color: '#ed9000' },
      { text: '        ' },
    ],
  },
  {
    segments: [
      { text: '    ' },
      { text: '.', color: '#55140f' },
      { text: ';;;;;;;', color: '#ea3829' },
      { text: ':', color: '#be2e21' },
      { text: '.', color: '#5a1510' },
      { text: '.', color: '#56150f' },
      { text: '.', color: '#5f1711' },
      { text: ':', color: '#9d261b' },
      { text: ';;;;;;', color: '#ea3829' },
      { text: '.', color: '#621711' },
      { text: ' ' },
      { text: ',', color: '#724500' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#704400' },
      { text: '         ' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#8b5400' },
      { text: '  ' },
      { text: '+', color: '#dc8500' },
      { text: '++++', color: '#f69500' },
      { text: '+', color: '#f59400' },
      { text: '+++++', color: '#f69500' },
      { text: ':', color: '#945a00' },
      { text: '+++++++++', color: '#f69500' },
      { text: '.', color: '#482c00' },
      { text: '       ' },
    ],
  },
  {
    segments: [
      { text: '    ' },
      { text: ':', color: '#94231a' },
      { text: ';;;;;;;', color: '#ea3829' },
      { text: '.', color: '#320c09' },
      { text: '    ' },
      { text: ':', color: '#b02a1f' },
      { text: ';;;;;', color: '#ea3829' },
      { text: ',', color: '#842017' },
      { text: ' ' },
      { text: ',', color: '#6a4000' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#724500' },
      { text: '        ' },
      { text: ' ', color: '#261700' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#8b5400' },
      { text: '  ' },
      { text: '+', color: '#f59500' },
      { text: '++++', color: '#f69500' },
      { text: ';', color: '#c97a00' },
      { text: '+', color: '#e58b00' },
      { text: '+++++++', color: '#f69500' },
      { text: '+', color: '#e18800' },
      { text: ';', color: '#b16b00' },
      { text: '+++++', color: '#f69500' },
      { text: ':', color: '#8e5600' },
      { text: '       ' },
    ],
  },
  {
    segments: [
      { text: '    ' },
      { text: ':', color: '#c22e22' },
      { text: ';;;;;;;', color: '#ea3829' },
      { text: '     ' },
      { text: ',', color: '#8c2219' },
      { text: ';;;;;', color: '#ea3829' },
      { text: ':', color: '#a4271d' },
      { text: ' ' },
      { text: ',', color: '#6a4000' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#643c00' },
      { text: '        ' },
      { text: ' ', color: '#261700' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#8b5400' },
      { text: ' ' },
      { text: '.', color: '#452a00' },
      { text: '+++++', color: '#f69500' },
      { text: ';', color: '#b06b00' },
      { text: ':', color: '#995d00' },
      { text: '+++++++', color: '#f69500' },
      { text: '.', color: '#4f3000' },
      { text: ',', color: '#6f4300' },
      { text: '+++++', color: '#f69500' },
      { text: ';', color: '#d58100' },
      { text: '       ' },
    ],
  },
  {
    segments: [
      { text: '    ' },
      { text: ';', color: '#cf3224' },
      { text: ';;;;;;;', color: '#ea3829' },
      { text: '     ' },
      { text: ',', color: '#6f1b13' },
      { text: ';;;;;', color: '#ea3829' },
      { text: ':', color: '#b62b20' },
      { text: ' ' },
      { text: ',', color: '#6d4200' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#603a00' },
      { text: '         ' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#8b5400' },
      { text: ' ' },
      { text: ',', color: '#754700' },
      { text: '+++++', color: '#f69500' },
      { text: ':', color: '#935900' },
      { text: '.', color: '#301d00' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#9a5d00' },
      { text: ' ' },
      { text: '.', color: '#311e00' },
      { text: '++++++', color: '#f69500' },
      { text: ' ', color: '#261700' },
      { text: '      ' },
    ],
  },
  {
    segments: [
      { text: '    ' },
      { text: ':', color: '#bf2e21' },
      { text: ';;;;;;;', color: '#ea3829' },
      { text: '     ' },
      { text: '.', color: '#4f130e' },
      { text: ';;;;;', color: '#ea3829' },
      { text: ':', color: '#ae2a1e' },
      { text: ' ' },
      { text: ',', color: '#6b4100' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#5e3900' },
      { text: '    ' },
      { text: ' ', color: '#2a1900' },
      { text: '.', color: '#321e00' },
      { text: '.', color: '#392300' },
      { text: '  ' },
      { text: '+', color: '#f59500' },
      { text: '+++++', color: '#f69500' },
      { text: ':', color: '#8d5500' },
      { text: ' ' },
      { text: ':', color: '#a56400' },
      { text: '+++++', color: '#f69500' },
      { text: ',', color: '#714500' },
      { text: ' ' },
      { text: ';', color: '#bb7100' },
      { text: '++++', color: '#f69500' },
      { text: ';', color: '#d48000' },
      { text: '   ' },
      { text: '+', color: '#f49400' },
      { text: '+++++', color: '#f69500' },
      { text: ',', color: '#6c4200' },
      { text: '      ' },
    ],
  },
  {
    segments: [
      { text: '    ' },
      { text: ',', color: '#761c15' },
      { text: ';;;;;;;', color: '#ea3829' },
      { text: ':', color: '#ac291e' },
      { text: '.', color: '#4d120d' },
      { text: '.', color: '#44100c' },
      { text: '.', color: '#49120d' },
      { text: ',', color: '#6b1a13' },
      { text: ';', color: '#cd3124' },
      { text: ';;;;;', color: '#ea3829' },
      { text: ':', color: '#97241a' },
      { text: ' ' },
      { text: ',', color: '#683f00' },
      { text: '++++++++++++++', color: '#f69500' },
      { text: ',', color: '#6c4100' },
      { text: ' ' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#a06100' },
      { text: ' ' },
      { text: ';', color: '#cc7c00' },
      { text: '+++++', color: '#f69500' },
      { text: '.', color: '#503100' },
      { text: ' ' },
      { text: '.', color: '#4f3000' },
      { text: '+++', color: '#f69500' },
      { text: '+', color: '#e48a00' },
      { text: '.', color: '#2e1c00' },
      { text: '   ' },
      { text: '+', color: '#df8700' },
      { text: '+++++', color: '#f69500' },
      { text: ';', color: '#bc7200' },
      { text: '      ' },
    ],
  },
  {
    segments: [
      { text: '     ' },
      { text: ',', color: '#872018' },
      { text: ';', color: '#e93829' },
      { text: ';;;;;;;;;;;;;;;', color: '#ea3829' },
      { text: ';', color: '#d23225' },
      { text: '  ' },
      { text: ',', color: '#663e00' },
      { text: '++++++++++++++', color: '#f69500' },
      { text: ',', color: '#7d4b00' },
      { text: ' ' },
      { text: '++++++', color: '#f69500' },
      { text: ':', color: '#8f5700' },
      { text: ' ' },
      { text: ':', color: '#8a5400' },
      { text: ':', color: '#a96700' },
      { text: ':', color: '#a56400' },
      { text: ':', color: '#9e6000' },
      { text: ':', color: '#945a00' },
      { text: ':', color: '#875200' },
      { text: ' ', color: '#261700' },
      { text: '  ' },
      { text: '.', color: '#452a00' },
      { text: ',', color: '#573500' },
      { text: '.', color: '#492c00' },
      { text: '     ' },
      { text: ':', color: '#845000' },
      { text: ':', color: '#a06100' },
      { text: ':', color: '#8f5700' },
      { text: ':', color: '#834f00' },
      { text: ',', color: '#794900' },
      { text: ',', color: '#5b3700' },
      { text: ' ', color: '#261700' },
      { text: '      ' },
    ],
  },
  {
    segments: [
      { text: '      ' },
      { text: ' ', color: '#2e0b08' },
      { text: ',', color: '#852017' },
      { text: ':', color: '#bf2e21' },
      { text: ';', color: '#e23628' },
      { text: ';;;;;;;;', color: '#ea3829' },
      { text: ';', color: '#e93829' },
      { text: ';', color: '#d43325' },
      { text: ':', color: '#a8281d' },
      { text: ',', color: '#651812' },
      { text: '   ' },
      { text: '.', color: '#543300' },
      { text: ':', color: '#9e6000' },
      { text: ':', color: '#9b5e00' },
      { text: ':', color: '#975b00' },
      { text: ':', color: '#935900' },
      { text: ':', color: '#8e5600' },
      { text: ':', color: '#8a5400' },
      { text: ':', color: '#865100' },
      { text: ':', color: '#824f00' },
      { text: ',', color: '#7e4c00' },
      { text: ',', color: '#7a4a00' },
      { text: ',', color: '#764700' },
      { text: ',', color: '#724500' },
      { text: ',', color: '#6e4200' },
      { text: ',', color: '#694000' },
      { text: '  ' },
      { text: '++++++', color: '#f69500' },
      { text: ',', color: '#784900' },
      { text: '                               ' },
    ],
  },
  {
    segments: [
      { text: '            ' },
      { text: ' ', color: '#2c0a08' },
      { text: ' ', color: '#300b08' },
      { text: '.', color: '#310c09' },
      { text: ' ', color: '#2e0b08' },
      { text: '                          ' },
      { text: '+', color: '#f59400' },
      { text: '+++++', color: '#f69500' },
      { text: ';', color: '#b36c00' },
      { text: ',', color: '#683f00' },
      { text: ',', color: '#6b4100' },
      { text: ',', color: '#734600' },
      { text: ',', color: '#724500' },
      { text: ',', color: '#704400' },
      { text: ',', color: '#6d4200' },
      { text: ',', color: '#694000' },
      { text: ',', color: '#663e00' },
      { text: '.', color: '#543300' },
      { text: '                      ' },
    ],
  },
  {
    segments: [
      { text: '                                          ' },
      { text: '+', color: '#f59500' },
      { text: '++++++++++++++', color: '#f69500' },
      { text: ';', color: '#cd7c00' },
      { text: '                      ' },
    ],
  },
  {
    segments: [
      { text: '                                         ' },
      { text: '.', color: '#2d1b00' },
      { text: '+++++++++++++++', color: '#f69500' },
      { text: ';', color: '#c97a00' },
      { text: '                      ' },
    ],
  },
  {
    segments: [
      { text: '                                                ' },
      { text: ' ', color: '#2b1a00' },
      { text: '.', color: '#321e00' },
      { text: '.', color: '#372100' },
      { text: '..', color: '#382200' },
      { text: '.', color: '#372100' },
      { text: '.', color: '#341f00' },
      { text: '.', color: '#321e00' },
      { text: '.', color: '#2e1c00' },
      { text: '                       ' },
    ],
  },
  {
    segments: [
      { text: '                                                                                ' },
    ],
  },
];
