export interface SnapshotObject {
  overallGoal: string;
  keyKnowledge: string[];
  fileSystemState: string[];
  currentPlan: string[];
}

export class SnapshotParser {
  /**
   * Parses the XML snapshot generated by the LLM.
   * Handles loose tagging and potential markdown wrapping.
   */
  static parse(content: string): SnapshotObject {
    // defined defaults
    const result: SnapshotObject = {
      overallGoal: '',
      keyKnowledge: [],
      fileSystemState: [],
      currentPlan: [],
    };

    // Remove markdown code blocks if present (```xml ... ```)
    const cleanContent = content.replace(/```(?:xml)?/g, '').trim();

    // Extract Overall Goal
    const goalMatch = cleanContent.match(/<overall_goal>([\s\S]*?)<\/overall_goal>/i);
    if (goalMatch) {
      result.overallGoal = goalMatch[1].trim();
    }

    // Helper to extract list items from a section
    const extractList = (tagName: string): string[] => {
      const regex = new RegExp(`<${tagName}>([\\s\\S]*?)</${tagName}>`, 'i');
      const match = cleanContent.match(regex);
      if (!match) return [];

      const chunk = match[1];
      // Split by newlines, filter out empty, remove leading non-alphanum (bullets)
      return chunk
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line.length > 0)
        .map((line) => line.replace(/^[-*•]\s?/, '').trim())
        .filter((line) => line.length > 0 && !line.startsWith('<!--'));
    };

    result.keyKnowledge = extractList('key_knowledge');
    result.fileSystemState = extractList('file_system_state');
    result.currentPlan = extractList('current_plan');

    return result;
  }

  /**
   * Converts a formatted SnapshotObject back into a system message content string
   * for reseeding the context.
   */
  static toSystemContext(snapshot: SnapshotObject): string {
    return `
# Previous Session Context (Restored)

## Overall Goal
${snapshot.overallGoal}

## Key Knowledge
${snapshot.keyKnowledge.map((k) => `- ${k}`).join('\n')}

## File System State
${snapshot.fileSystemState.map((f) => `- ${f}`).join('\n')}

## Current Plan
${snapshot.currentPlan.map((p) => `- ${p}`).join('\n')}
`.trim();
  }
}
